### ISSUE TITLE
上传不成功

### ISSUE THREAD

**Issue by mjnhmd** [xzop/markdown-img-upload-windows#1]
我按照你的要求做的 单后点击ctrl+alt+c之后弹出的窗口闪一下就立刻没了，然后再文本里ctrl+v什么都没有，在桌面上ctrl+v 直接把图片复制了 ，我看七牛里并没有上传上去。这个有没有日志什么的啊

**Comment by mjnhmd** [comment]
Traceback (most recent call last):
  File "D:/qiniu/upload_qiniu.py", line 52, in <module>
    ahk = cdll.AutoHotkey #load AutoHotkey
  File "D:\Python27\lib\ctypes__init__.py", line 435, in **getattr**
    dll = self._dlltype(name)
  File "D:\Python27\lib\ctypes__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

看到日志了。我去 我又安了个IDE，又看了看python的基础语法。。。
这个是不是因为我引入的autohotkey.dll不对啊？我电脑是win10 64位的不久引入那个64位的吗

**Comment by xzonepiece** [comment]
将ahk文件中的/c换成/k，cmd窗口就不会一闪而过了，也可以看看错在哪里
